FROM container-registry.oracle.com/os/oraclelinux:8

COPY rpms /tmp/
RUN dnf install -y /tmp/*.rpm && \
    dnf clean all && \
    rm -rf /var/cache/yum/* /tmp/*.rpm

FROM container-registry.oracle.com/os/oraclelinux:8-slim

COPY --from=0 /usr/share/licenses/prometheus-operator /usr/share/licenses/prometheus-config-reloader
COPY --from=0 /usr/bin/prometheus-config-reloader /usr/bin/prometheus-config-reloader

RUN microdnf update -y && \
    microdnf clean all && \
    rm -rf /var/cache/yum/* && \
    test -d /LICENSES || ln -s /usr/share/licenses /LICENSES

USER nobody

ENTRYPOINT  [ "/usr/bin/prometheus-config-reloader" ]
