FROM container-registry.oracle.com/os/oraclelinux:8

COPY rpms /tmp/
RUN dnf install -y /tmp/*.rpm && \
    dnf clean all && \
    rm -rf /var/cache/yum/* /tmp/*.rpm

FROM container-registry.oracle.com/os/oraclelinux:8-slim

COPY --from=0 /usr/bin/prometheus-admission-webhook /usr/bin/prometheus-admission-webhook

USER nobody

ENTRYPOINT ["/usr/bin/prometheus-admission-webhook"]
