FROM container-registry.oracle.com/os/oraclelinux:9 AS builder

RUN dnf config-manager --enable ol9_codeready_builder && \
    dnf -y install git make golang hostname && \
    go version

# Copy the contents of the repository
COPY . /workspace/go/src/github.com/oracle-cne/prometheus-operator

ENV GOPATH=/workspace/go CGO_ENABLED=0
ENV GOPATH_SRC=$GOPATH/src/github.com/oracle-cne/prometheus-operator
WORKDIR /workspace/go/src/github.com/oracle-cne/prometheus-operator

RUN git config --global --add safe.directory $(pwd) && \
    sh olm/go-build.sh

FROM container-registry.oracle.com/os/oraclelinux:9-slim

COPY LICENSE THIRD_PARTY_LICENSES.txt olm/SECURITY.md /usr/share/licenses/prometheus-admission-webhook
COPY --from=builder bin/prometheus-admission-webhook /usr/bin/prometheus-admission-webhook

USER nobody

ENTRYPOINT ["/usr/bin/prometheus-admission-webhook"]
